#! /bin/sh

sxhkd &

bspc monitor HDMI-1 -n 0 -d I II III IV V
bspc monitor DP-2 -n 0 -d VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Desktop 1: Terminal
#bspc rule -a Termite desktop='^1'

# Desktop 2: Browser
#bspc rule -a Google-chrome desktop='^2'

# Desktop 3: Coding
#bspc rule -a jetbrains-idea desktop='^3'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

~/.config/polybar/launch.sh
./bspwm-startup.sh
